### ISSUE TITLE
Question API prefix like /api/v1/

### ISSUE THREAD

**Issue by alduro** [jarradseers/consign#4]
Hi, let's suppose I want to prefix my routes with /api/v1 and I have this config file:

``` javascript
import express from 'express';
import consign from 'consign';

const app = express();

consign({ verbose: false })
  .include('libs/config.js')
  .then('db.js')
  .then('auth.js')
  .then('libs/middlewares.js')
  .then('routes')
  .then('libs/boot.js')
  .into(app);

module.exports = app;
```

and my routes definition does not start using a prefix, like:

`````` javascript
import async from 'async';
import crypto from 'crypto';
import nodemailer from 'nodemailer';
import { EmailTemplate } from 'email-templates';
import path from 'path';

module.exports = app => {
  const cfg = app.libs.config;
  const Users = app.db.models.Users;

  app.route('/user')
    .all(app.auth.authenticate())
    /**```

How can I do it ?
``````

**Comment by Opligitory** [comment]
possibly like this 
```javascript
  app.get('/user/v1')
```
just an idea

**Comment by jarradseers** [comment]
I'm not sure exactly what you are trying to achieve here sorry, please see the examples folder for usage

**Comment by NegativeIQ** [comment]
https://gist.github.com/focusaurus/5779340
Check out that sub-app pattern, its actually pretty awesome for quick API versioning, but keep in mind it will be a nightmare in longer run on big app. So if its api for personal use (just for angular and maybe some smartphone app) then you are fine, if you want api to be public and documented better use Restify since its why it was build for and it has best api versioning system i have seen.

**Comment by scarsnik** [comment]
Between your Middleware and Routes add a routing.js file

```
.then('libs/middlewares.js')
.then('routing.js')
.then('routes')
```

The routing.js file basically contains your router middleware:
```
'use strict';
var router = require("express").Router();

module.exports = function(app) {
    app.use("/api/v1", router);
    return router;  
};
```

Then to use the routing:
```
const Router = app.routing
Router.route('/user')
    .all(app.auth.authenticate())
    ...
```
